// Mocks generated by Mockito 5.4.6 from annotations
// in sleep_management_app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:sleep_management_app/services/supabase_ranking_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SupabaseRankingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseRankingService extends _i1.Mock
    implements _i2.SupabaseRankingService {
  MockSupabaseRankingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String getLogicalDateInJST() =>
      (super.noSuchMethod(
            Invocation.method(#getLogicalDateInJST, []),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#getLogicalDateInJST, []),
            ),
          )
          as String);

  @override
  _i4.Future<List<Map<String, dynamic>>> getRanking({String? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getRanking, [], {#date: date}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getRankingWithQuotes({String? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getRankingWithQuotes, [], {#date: date}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> submitRecord({
    required String? userId,
    required String? dataId,
    required int? sleepDuration,
    required String? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitRecord, [], {
              #userId: userId,
              #dataId: dataId,
              #sleepDuration: sleepDuration,
              #date: date,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUser({
    required String? id,
    required String? username,
    String? backgroundPreference,
    int? sleepCoins,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [], {
              #id: id,
              #username: username,
              #backgroundPreference: backgroundPreference,
              #sleepCoins: sleepCoins,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserAiTone({
    required String? userId,
    required String? aiTone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserAiTone, [], {
              #userId: userId,
              #aiTone: aiTone,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserAiGender({
    required String? userId,
    required String? aiGender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserAiGender, [], {
              #userId: userId,
              #aiGender: aiGender,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getUnlockedBackgrounds(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnlockedBackgrounds, [userId]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> purchaseBackground({
    required String? userId,
    required String? backgroundId,
    required int? cost,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#purchaseBackground, [], {
              #userId: userId,
              #backgroundId: backgroundId,
              #cost: cost,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deductCoinsForGacha(
    String? userId,
    int? cost,
    int? pullCount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deductCoinsForGacha, [userId, cost, pullCount]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> purchaseGachaTicket({
    required String? userId,
    required int? cost,
    required String? ticketType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#purchaseGachaTicket, [], {
              #userId: userId,
              #cost: cost,
              #ticketType: ticketType,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> consumeUltraRareTicket(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#consumeUltraRareTicket, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setFavoriteQuote(String? userId, String? quoteId) =>
      (super.noSuchMethod(
            Invocation.method(#setFavoriteQuote, [userId, quoteId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateSleepCoins({
    required String? userId,
    required int? coinsToAdd,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSleepCoins, [], {
              #userId: userId,
              #coinsToAdd: coinsToAdd,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAiScoreRanking({String? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getAiScoreRanking, [], {#date: date}),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);
}
